AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with versioning enabled.

Parameters:
  BucketName:
    Description: "The name of the S3 bucket (must be unique across all existing S3 buckets)"
    Type: String
    
Resources:
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  SampleS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: 
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource: "arn:aws:s3:::sample-vis-bkt/*"     
Outputs:
  BucketName:
    Value: !Ref BucketName
    Description: "Name of the created S3 bucket"
